### ISSUE TITLE
Support pypy

### ISSUE THREAD

**Issue by domenkozar** [zopefoundation/zope.sqlalchemy#12]
- run tests on travis-ci
- fix failing test (using sqlalchemy 0.7.x):

```
======================================================================
FAIL: /tmp/nix-build-pypy2.3-zope.sqlalchemy-0.7.5.drv-0/zope.sqlalchemy-0.7.5/src/zope/sqlalchemy/README.txt
Doctest: README.txt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/p4rfgk7an0x6vb04v48vzb4r0z3b84cw-pypy-2.3.1/pypy-c/lib-python/2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for README.txt
  File "/tmp/nix-build-pypy2.3-zope.sqlalchemy-0.7.5.drv-0/zope.sqlalchemy-0.7.5/src/zope/sqlalchemy/README.txt", line 0

----------------------------------------------------------------------
File "/tmp/nix-build-pypy2.3-zope.sqlalchemy-0.7.5.drv-0/zope.sqlalchemy-0.7.5/src/zope/sqlalchemy/README.txt", line 177, in README.txt
Failed example:
    str(session.query(User).all()[0].name)
Expected:
    'bob'
Got:
    'ben'
```

**Comment by icemac** [comment]
Locally tox runs successfully for PyPy2. PyPy3 shows the same error as above. So at least PyPy2 support could be added.
