### ISSUE TITLE
Tests fail with AssertionError: Not joined transaction

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.sqlalchemy#17]
See https://travis-ci.org/zopefoundation/zope.sqlalchemy/builds/139672322:

```
Failure in test testTransactionJoining (zope.sqlalchemy.tests.ZopeSQLAlchemyTests)
Traceback (most recent call last):
  File "/opt/python/3.3.6/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/home/travis/build/zopefoundation/zope.sqlalchemy/src/zope/sqlalchemy/tests.py", line 344, in testTransactionJoining
    "Not joined transaction")
  File "/opt/python/3.3.6/lib/python3.3/unittest/case.py", line 520, in assertTrue
    raise self.failureException(msg)
AssertionError: [] is not true : Not joined transaction
```

(and a few other test failures with the same assertion error)

**Comment by icemac** [comment]
`transaction >= 1.5` seems to break these tests. See #19.

**Comment by icemac** [comment]
Closing an favour of #20
